name: Auto Newsletter

on:
  schedule:
    - cron: '0 9 * * 1-5'  # Runs every weekday at 9:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen es_ES.UTF-8
          sudo update-locale LANG=es_ES.UTF-8
        shell: bash

      - name: Run main.py
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
        run: python main.py
